services:
  - type: web
    name: timecard-api
    runtime: docker
    repo: https://github.com/gplans73/timecard-api
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /
